### ISSUE TITLE
[Bug]: Traefik cannot resolve instance

### ISSUE THREAD

**Issue by dreamwhite** [actualbudget/actual#1736]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I'm running Actual Budget using the following `docker-compose.yml` file:

```yaml
version: '3.3'
services:
  my_actual_budget:
    image: actualbudget/actual-server:latest
    container_name: my_actual_budget
    restart: always
#    ports: <-------------------------- Commented this section since Traefik can detect internal docker container ports
#      - "5006:5006"

    volumes:
      - ./data:/data
    labels:
      - traefik.http.routers.actual-budget.rule=Host(`actual.my_domain.com`)
      - traefik.port=5006
      - traefik.http.routers.actual-budget.tls=true
      - traefik.http.routers.actual-budget.tls.certresolver=lets-encrypt
    networks:
      - web

networks:
  web:
    external: true
```

Visiting my domain leads to a generic error 404, but if I open the ports I can correctly reach the service (`my_domain.com:5006`).

I had similar issues with other applications served via Docker, but in the majority of cases setting the `APP_URL` environment variable seemed to do the trick. Is there anything similar on this project?

Thanks in advance :)
dreamwhite 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Desktop App (Electron), Other

### Operating System

Mac OSX

**Comment by hkamran80** [comment]
I use this configuration in my Compose file.

```yaml
labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`actual.mydomain.com`)"
      - "traefik.http.routers.actual.entrypoints=websecure"
      - "traefik.http.routers.actual.tls.certresolver=letsencrypt"
```

**Comment by dreamwhite** [comment]
I still get a `Bad Gateway` error. Don't know why. Can you please attach your docker-compose.yml?

**Comment by hkamran80** [comment]
Sure.

```yaml
services:
  actual_server:
    image: actualbudget/actual-server:latest
    container_name: actual-server
    restart: unless-stopped
    networks:
      - traefik_default
    environment:
      ACTUAL_NORDIGEN_SECRET_ID: [redacted]
      ACTUAL_NORDIGEN_SECRET_KEY: [redacted]
    volumes:
      - ./actual-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`actual.mydomain.com`)"
      - "traefik.http.routers.actual.entrypoints=websecure"
      - "traefik.http.routers.actual.tls.certresolver=letsencrypt"

networks:
  traefik_default:
    external: true
```

**Comment by dreamwhite** [comment]
Alright. I'm using the following `docker-compose.yml` file but when I visit `actual.mydomain.com` I get a HTTP error 502 Bad Gateway.

```yaml
version: '3.8'
services:
  my_actual_budget:
    image: actualbudget/actual-server:latest
    container_name: my_actual_budget
    restart: always
    volumes:
      - ./data:/data
    labels:
      - traefik.http.routers.actual-budget.rule=Host(`actual-budget.mydomain.com`)
      - traefik.port=5006
      - traefik.http.routers.actual-budget.tls=true
      - traefik.http.routers.actual-budget.tls.certresolver=lets-encrypt
    networks:
      - web

networks:
  web:
    external: true
```

What's wrong?
