### ISSUE TITLE
[Bug]: Error while updating docker Image 2023.12.0

### ISSUE THREAD

**Issue by nmathey** [actualbudget/actual#2011]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

While updating docker image with latest tag 2023.12.0, the container is not able to start properly and crash.

### What error did you receive?

```
Node.js v18.19.0
Checking if there are any migrations to run for direction "up"...
file:///app/src/migrations.js:21
            throw err;
            ^
[Error: EACCES: permission denied, open '.migrate'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '.migrate'
}

```

### Where are you hosting Actual?

Docker

### Operating System

Other

**Comment by reesehopkins** [comment]
Running into the same issue. I am running on Synology NAS using [these instructions](https://mariushosting.com/how-to-install-actual-on-your-synology-nas/)

**Comment by carpenike** [comment]
Having the same issue with 
```
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 23.12.0
```

**Comment by pogora** [comment]
Same here. 
Even created a new clone with empty folders. Still the same.
Going back to: `ghcr.io/actualbudget/actual-server:23.11.0`
Gets everything back and working with the previous version. So at least you can keep working.

**Comment by fopoku2k2** [comment]
I also have the same issue. I am using docker on synology nas with the actualbudget/actual-server docker account

**Comment by youngcw** [comment]
I run Actual on my synology box and this is the docker-compose I use.  I haven't had any issues that weren't my own doing with it. Edit the image and volumes to match your desired setup
```
version: "3"                                                                    
services:
  actual_server:
    image: actualbudget/actual-server:edge
    container_name: actual_budget
    network_mode: bridge
    ports:
      - "5006:5006"
    environment:
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=50
      #- ACUTAL_HTTPS_KEY=/data/selfhost.key
      #- ACUTAL_HTTPS_CERT=/data/selfhost.crt
    volumes:
      - ./data:/data
    restart: unless-stopped
```

**Comment by fopoku2k2** [comment]
works. thanks for the quick fix

**Comment by nmathey** [comment]
Working like a charm! 
I guess this issue can be close as is since the problem was more related to an installation type rather than Actua itself?

**Comment by samcre** [comment]
> Hi everyone. That [guide from Marius Hosting](https://mariushosting.com/how-to-install-actual-on-your-synology-nas/) has been updated. My recommended process, if you are still having issues, would be to:
> 
>     1. Revert to 23.11.0 and export your data as a backup
> 
>     2. follow the new setup process in the guide
> 
>     3. pull the updated docker container
> 
>     4. if needed, import your exported budget.
> 
> 
> That should get passed the issue of missing the .migration file and not having proper permissions.

If I understand the workflow of the app correctly, mounting the path `/data` of the container on your host will not fail on the start-up. But your `server-files` and `user-files` will be ONLY on the container, so you will lose them at any point. Please correct me if I'm wrong. Longtime user of docker and containers, but not so sure about Actual's behavior.

> 👋
> 
> I followed the install instructions [here](https://github.com/actualbudget/actual/issues/2011#issuecomment-1837295607) and I think for v23.12.0 you will want to change a few things in those instructions to be more stable.
> 
> On step 11: do not create any folders.
> 
> On step 13: remove the `volumes` argument. Instead use this:
> 
> ```
> volumes:
>       - /volume1/docker/actual:/app
> ```
> 
> This should mount the entire folder. At which point it should be able to run the migrations that will automatically create the `server-files` and `user-files` folders inside there (if they are not already there).
> 
> If someone could try doing this and letting me know if that works - I'd very much appreciate it.

I tried this config on my Synology NAS, and it doesn't work. When you mount your host's `/volume1/docker/actual` onto your containers' `/app`, inside the container, the content of the `/app` directory is empty because it contains the **host** directory, which is empty on a new installation.

What it worked for me is to manually create the `.migrate` file on your host, and mount it directly to the container, like this:

```
    volumes:
      - ${BASE_DIR}/docker/actualbudget/server-files:/app/server-files
      - ${BASE_DIR}/docker/actualbudget/user-files:/app/user-files
      - ${BASE_DIR}/docker/actualbudget/.migrate:/app/.migrate
```

With this config, the container start-up without problems because the `.migrate` file already exist.

In the long term, it would be a good idea to store this `.migrate` file inside `server-files` directly, or use a table inside an already created SQLite database, and store migration on that table.

**Comment by samcre** [comment]
> I'm still having this issue and I've tried the solutions in this thread. Mounting my docker dir as `/data` or `/app` doesn't seem to make a difference, and the container won't stay alive long enough for me to get to the console inside it.
> 
> If I need to make the `.migrate` file manually, where would it go? Currently my docker dir just contains `server-files` and `user-files`, I tried a `.migrate` file alongside those two and didn't seem to work.

The `.migrate` file should be alongside the directories `server-files` and `user-files`, just like this:

```bash
$ pwd
/volume1/docker/actualbudget
$ ls -la
total 4
drwxrwxrwx+ 1 user users  60 Dec  4 08:28 .
drwxrwxrwx+ 1 root          root  360 Nov 17 10:08 ..
-rwxrwxrwx+ 1 user users 373 Dec  4 08:28 .migrate
drwxrwxrwx+ 1 user users  28 Dec  4 08:27 server-files
drwxrwxrwx+ 1 user users 950 Dec  4 09:32 user-files
```

You can create the file simply using `touch .migrate` (be sure to use the same user that will run the docker container), and mount it inside the container with this `docker-compose` config:

```yaml
    volumes:
      - /volume1/docker/actual/server-files:/app/server-files
      - /volume1/docker/actual/user-files:/app/user-files
      - /volume1/docker/actual/.migrate:/app/.migrate
```

If you face any error, send us the log, so we can help you. 😊

**Comment by samip5** [comment]
> As it turns out: some set-ups don't allow writing this `.migrate` file in the root actual directory. I think the esiest solution for Synology NAS users is [this comment](https://github.com/actualbudget/actual/issues/2011#issuecomment-1837520489). But if there are other ideas - lets chat. And obviously PRs are welcome :)

It might be a good time as any to move to an SQL query builder maybe? 
Eg. https://knexjs.org which would allow to support Postgres and sqlite aswell as database-agostic migrations. :)

**Comment by ajfromuk** [comment]
> Hi everyone. That [guide from Marius Hosting](https://mariushosting.com/how-to-install-actual-on-your-synology-nas/) has been updated. My recommended process, if you are still having issues, would be to:
> 
> 1. Revert to 23.11.0 and export your data as a backup
> 2. follow the new setup process in the guide
> 3. pull the updated docker container
> 4. if needed, import your exported budget.
> 
> That should get passed the issue of missing the .migration file and not having proper permissions.

I am honestly going to sound like a noob and I have been searching online but how to I revert the container to 23.11.0. I'm trying to recreate it and point the image to actualbudget/actual-server:23.11.0 but each time I click create it just doesnt pull it down and loads the current one I have installed.

**Comment by samip5** [comment]
Hey @MatissJanis, it think the migration file shouldn't live in the app root as if anybody is running this non-privileged, they don't have any way to write to things there.

**Comment by bjw-s** [comment]
I've created https://github.com/actualbudget/actual-server/pull/289 that will have the server store the migrations file in the dataDir instead of the application root

**Comment by samip5** [comment]
> Could someone please verify if the patch @bjw-s has graciously provided fixes the issue for you? https://github.com/actualbudget/actual-server/pull/289
> 
> On my machine it works as expected (but TBH it worked fine before too).

Could you please push the container with it? It seems PR's are built but not pushed.

**Comment by bjw-s** [comment]
> > Could someone please verify if the patch @bjw-s has graciously provided fixes the issue for you? [actualbudget/actual-server#289](https://github.com/actualbudget/actual-server/pull/289)
> > On my machine it works as expected (but TBH it worked fine before too).
> 
> Could you please push the container with it? It seems PR's are built but not pushed.

https://github.com/users/bjw-s/packages/container/actual-server/154582722?tag=pr-289

**Comment by samip5** [comment]
I have tested the container and it does indeed now go to the /data path, which is writable and works as one would expect it to.

```
actual-0:/data$ ls -al
total 8
drwxrwsr-x 4 root  568   60 Dec  5 10:02 .
drwxr-xr-x 1 root root 4096 Dec  5 10:02 ..
-rw-r--r-- 1  568  568  373 Dec  5 10:02 .migrate
drwxr-sr-x 2  568  568   28 Dec  5 10:02 server-files
drwxr-sr-x 2  568  568    6 Dec  5 10:02 user-files
```

**Comment by pogora** [comment]
> Hi everyone. That [guide from Marius Hosting](https://mariushosting.com/how-to-install-actual-on-your-synology-nas/) has been updated. My recommended process, if you are still having issues, would be to:
> 
> 1. Revert to 23.11.0 and export your data as a backup
> 2. follow the new setup process in the guide
> 3. pull the updated docker container
> 4. if needed, import your exported budget.
> 
> That should get passed the issue of missing the .migration file and not having proper permissions.

That worked for me as well.

**Comment by pogora** [comment]
> ly going to sound like a noob and I have been searching online but how to I revert the container to 23.11.0. I'm trying to recreate it and point the image to actualbudget/actual-server:23.11.0 but each time I click create it just doesnt pull it down and loads the current one I have installed.

That would depend on the software you use to manage your Docker.  Personally I'd recommend Dockge or Portainer.
Then you need to create 2 containers 1. actualbudget-old  and 2. actualbudget with the latest version.

Personally I prefer Dockge it's got a very simple UI and you can also add convert "docker run". It looked like this for me:
![2023-12-05 15_59_23-Dockge - 192 168 147 3_8010 - Vivaldi](https://github.com/actualbudget/actual/assets/35605240/a8df5992-ef00-4c93-9bbb-1cd1b46d879e)

1. actualbudget-old:

```
version: "3.9"
services:
  actualbudget-old:
    image: ghcr.io/actualbudget/actual-server:23.11.0-alpine
    # image: actualbudget/actual-server:23.10.0
    container_name: actualbudget-old
    security_opt:
      - no-new-privileges:true
    ports:
      - #yourport#:5006
    volumes:
      - /volume2/docker/actual/server:/app/server-files
      - /volume2/docker/actual/user:/app/user-files
    restart: unless-stopped
networks: {}

```

2. actualbudget:latest
```
version: "3.9"
services:
  actualbudget:
    image: ghcr.io/actualbudget/actual-server:latest-alpine
    container_name: actualbudget
    security_opt:
      - no-new-privileges:true
    ports:
      - #yourport#:5006
    volumes:
      - /volume1/docker/actualbudget:/data
    restart: unless-stopped
networks: {}

```
Then as mentioned by the guide before just export the data and import it to the latest version. After that you can delete the actualbudget-old container.
