### ISSUE TITLE
[Bug]: Container Fails to Start With Node Error

### ISSUE THREAD

**Issue by b-dont** [actualbudget/actual#2086]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I'm attempting to run an Actual server on my Raspberry Pi 4, however the container is failing to start with a Node.js error. Here's my machine specs:
```
OS: Raspbian GNU/Linux 10 (buster) armv7l
Host: Raspberry Pi 4 Model B Rev 1.2
Kernel: 5.10.103-v7l+
CPU: BCM2711 (4) @ 1.500GHz
Memory: 573MiB / 3838MiB
```
`Docker version 24.0.7, build afdd53b`
`docker-compose.yml`:
```
version: '3'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    environment:
      # Uncomment any of the lines below to set configuration options.
      - ACTUAL_HTTPS_KEY=/data/selfhost.key
      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ./actual-data:/data
    restart: unless-stopped
```

### What error did you receive?

```
btp@pihole:~/apps/actual-server $ docker-compose up
Creating network "actual-server_default" with the default driver
Creating actual-server_actual_server_1 ... done
Attaching to actual-server_actual_server_1
actual_server_1  | Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
actual-server_actual_server_1 exited with code 134
actual_server_1  | Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
actual_server_1  | Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
actual_server_1  | Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
actual-server_actual_server_1 exited with code 134
```
```
btp@pihole:~/apps/actual-server $ docker logs -f actual-server_actual_server_1
Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Node.js[7]: ../src/util.cc:193:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Linux
