### ISSUE TITLE
"Unable to save changes"

### ISSUE THREAD

**Issue by slater1** [actualbudget/actual#365]
If I import a brand-new YNAB4 budget (via zip file), close the budget, and reopen it, I am greeted with the error:

```
Unable to save changes
This browser only supports using the app in one tab at a time, and another tab has opened the app. No changes will be saved from this tab; please close it and continue working in the other one.
```

![image](https://user-images.githubusercontent.com/2089725/166069564-f8705e42-fc29-403a-bad6-9719d65dcd1e.png)

Here is the budget. There is one account with one transaction. [test~9F711BFB.ynab4.zip](https://github.com/actualbudget/actual-server/files/8594710/test.9F711BFB.ynab4.zip)

I only have one tab open. Change do actually save. Verified by checking the sqlite db.

I'm using Firefox 99.0.1 on Windows 10 19043. Doesn't seem to happen on Chrome 100.0.4896.127 even while the Firefox tab is still open and even if I open two tabs to Actual in Chrome. 

Budget attached.

**Comment by MatissJanis** [comment]
👋 I believe we have fixed the issue and it will be OK in the upcoming release since I'm no longer able to reproduce the issue with the example file.

**Comment by UnaDeKalamares** [comment]
I'm sorry to resurrect this issue trying to self-host on Docker Compose, but I'm seeing the same error on the latest release (v25.2.1). This ere the steps I follow:

- Create the following compose file:

```
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - /srv/mergerfs/RaspiNAS/Compose-Data/actual-budget/actual-data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
```

_I'm storing the server data behind a mergerfs file system_
_Please notice that I'm not using HTTP, at least for this tests. The server only runs locally._

- Start the application, and open the url from a client (I've tried Firefox 135.0.1 and Safari 18.3 on MacOS)

- I'm prompted to enter a new server password and then Sign in:

![Image](https://github.com/user-attachments/assets/f6268aa2-b376-4ede-a617-42f634ee61d1)

- I select "Start fresh"

- I immediately get the "Unable to save changes" error popup, even though no other tab is open

![Image](https://github.com/user-attachments/assets/16a66fc3-ff66-4e9e-bcb0-d0ed232bf74b)

- If I refresh the page, I get an unknown problem:

![Image](https://github.com/user-attachments/assets/0e4ee07e-12b6-4ea7-8cdb-baa370e95c9b)

Is there anything I might be missing here? I'm running other applications (Syncthing, Home Assistant) in this Docker Compose setup with no issues.

Thank you for your time.
