### ISSUE TITLE
[Bug]: Certificates not working in edge version

### ISSUE THREAD

**Issue by mauroartizzu** [actualbudget/actual#4687]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

If i switch to edge tag in my docker-compose.yaml file I can not access the server

![Image](https://github.com/user-attachments/assets/2c38d788-b8ce-4696-8b2f-e14491bf6b75)

Certificates are valid and work fine in latest

```
services:
  actual:
    image: docker.io/actualbudget/actual-server:latest
    # image: docker.io/actualbudget/actual-server:edge
    ports:
      - '5006:5006'
    environment:
      - ACTUAL_HTTPS_KEY=/certs/myhost.key
      - ACTUAL_HTTPS_CERT=/certs/myhost.crt
      - ACTUAL_PORT=5006
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20

    volumes:
      - actual_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/CACHEDEV1_DATA/.qpkg/Tailscale:/certs
    restart: unless-stopped

volumes:
  actual_data:
```

### How can we reproduce the issue?

switch from latest to edge in a dockerized environment

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Other
