### ISSUE TITLE
[Bug]: Unable to decrypt a file with this password. Try again... Docker

### ISSUE THREAD

**Issue by gwynnbleiidd** [actualbudget/actual#4698]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

After installing docker, the web starts with the error Unable to decrypt a file with this password. Try again...

```
services:
  actual_server:
    image: ghcr.io/actualbudget/actual:latest
    ports:
      - '5006:5006'
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - /Volumes/trash/actual:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
```

### How can we reproduce the issue?

I install it through Portainer, using Stacks.

Then I open the web on port 5006

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX
