### ISSUE TITLE
[Bug]: Docker compose setup not pulling files

### ISSUE THREAD

**Issue by mrjohnnycake** [actualbudget/actual#4718]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

I've setup Actual using your docker compose file and it's not pulling down any app files so the loading page can't find any server. Opening the page at http://my-local-ip:5006 it loads the background but just says "Initializing the connection to the local database..." and does nothing else.

First I'll show you my compose file:

```
services:
  actual_server:
    container_name: actualbudget
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
	  - /opt/docker/actualbudget:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
```

Now here the tree of directories and files running that makes:

```
actual
|____.migrate
|____server-files
| |____account.sqlite
|____user-files
|____compose.yaml
```

I've read through the documentation for running with Docker but I can't see what I've missed. I'm guessing that the dockerfile is supposed to pull down more files but that's just my guess.

To test my ability to follow your docs I ran the setup for installing on Fly.io and it works fine on there. I connected to the fly.io console and can see a lot more files on that server than what are appearing on mine. Is the dockerfile not working correctly or did I do something wrong? I'm usually pretty good at troubleshooting Docker compose files so I'm lost on this one.

Thanks.

### How can we reproduce the issue?

To reproduce the issue:

- On a basic Debian VM (I'm using Proxmox as my hypervisor), make a directory for app.
- I keep my compose files in the app's directory as seen in my directory tree
- The app directory and the compose file are owned by my main user and that user is in the docker group
- Run the compose file with `docker compose up -d`
- Open the Actual webpage with http://server-ip:5006

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11
