### ISSUE TITLE
[Bug]: Rejection: TypeError: invalid IP address:  10.0.222.222

### ISSUE THREAD

**Issue by raldone01** [actualbudget/actual#4764]
### What happened?

Previously this configuration was working.
The ip in question looks pretty valid to me.
Maybe there is some whitespace around it?

```
actual_server-1  | Checking if there are any migrations to run for direction "up"...
actual_server-1  | Migrations: DONE
actual_server-1  | Rejection: TypeError: invalid IP address:  10.0.222.222
actual_server-1  |     at parseipNotation (/app/node_modules/proxy-addr/index.js:163:11)
actual_server-1  |     at compileRangeSubnets (/app/node_modules/proxy-addr/index.js:126:23)
actual_server-1  |     at Function.compile (/app/node_modules/proxy-addr/index.js:112:23)
actual_server-1  |     at exports.compileTrust (/app/node_modules/express/lib/utils.js:234:20)
actual_server-1  |     at Function.set (/app/node_modules/express/lib/application.js:389:34)
actual_server-1  |     at file:///app/src/app.js:28:5
actual_server-1  | Checking if there are any migrations to run for direction "up"...
actual_server-1  | Migrations: DONE
actual_server-1  | Rejection: TypeError: invalid IP address:  10.0.222.222
actual_server-1  |     at parseipNotation (/app/node_modules/proxy-addr/index.js:163:11)
actual_server-1  |     at compileRangeSubnets (/app/node_modules/proxy-addr/index.js:126:23)
actual_server-1  |     at Function.compile (/app/node_modules/proxy-addr/index.js:112:23)
actual_server-1  |     at exports.compileTrust (/app/node_modules/express/lib/utils.js:234:20)
actual_server-1  |     at Function.set (/app/node_modules/express/lib/application.js:389:34)
actual_server-1  |     at file:///app/src/app.js:28:5
actual_server-1  | Checking if there are any migrations to run for direction "up"...
actual_server-1  | Migrations: DONE
```

### How can we reproduce the issue?

```yml
services:
  actual_server:
    extends:
      file: docker-compose-extends.yml
      service: base_service
    image: docker.io/actualbudget/actual-server:latest
    #ports:
      #- '5006:5006'
    environment:
      - ACTUAL_TRUSTED_PROXIES=2a02:redacted:redacted:redacted:redacted:redacted:redacted:redacted/128, 10.0.222.222/32
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      - ${CONTAINER_SSD}/comp_actual/data:/data
    networks:
      behind-nginx-ip:
          ipv4_address: 10.0.222.13
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Linux
