### ISSUE TITLE
Add a Dark Mode

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#618]
It would be nice to have a dark theme so Actual isn’t so bright at night.

**Comment by miclgael** [comment]
A quick lo-fi solution is to implement some custom CSS in the browser.

```css
html {
   filter: invert() contrast(0.8) brightness(1.1);
}
```

Not the greatest design, but will save your eyes while devs work on proper themes. 

![image](https://user-images.githubusercontent.com/4301358/230521791-4ed8e82b-6a52-42b6-9a1e-2e92f7c73ab3.png)

**Comment by j-f1** [comment]
If you add `hue-rotate(0.5turn)` in there it will do its best to render the colors correctly.

**Comment by miclgael** [comment]
@j-f1 oooo thats nice! Thanks. I updated the snip.

```css
html {
   filter: invert() contrast(0.8) brightness(1.1) hue-rotate(0.5turn)
}
```

![image](https://user-images.githubusercontent.com/4301358/230535405-ebb2cc9a-fecb-4b87-92cb-e0316b63d17f.png)
